export const CONTENT_TYPES = ["Reply", "Post", "Thread", "Article"] as const;
export type ContentType = (typeof CONTENT_TYPES)[number];

export const DRAFT_STATUSES = ["draft", "packaged", "scheduled", "posted"] as const;
export type DraftStatus = (typeof DRAFT_STATUSES)[number];

export const SLOT_STATUSES = ["empty", "filled", "posted"] as const;
export type SlotStatus = (typeof SLOT_STATUSES)[number];

export const SLOT_TYPES = ["Reply", "Post", "Thread", "Article"] as const;
export type SlotType = (typeof SLOT_TYPES)[number];

export interface Draft {
  id: string;
  title: string;
  contentType: ContentType;
  status: DraftStatus;
  pinned: boolean;
  updatedAt: Date;
}

export interface ScheduledSlot {
  id: string;
  date: Date;
  timeSlot: string;
  slotType: SlotType;
  status: SlotStatus;
  draftId?: string;
  draftTitle?: string;
  postedAt?: Date;
}

export type MessageRole = "user" | "assistant";

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  createdAt: Date;
}

export interface Note {
  id: string;
  content: string;
  createdAt: Date;
}

export const SUPPORTED_LANGUAGES = [
  { value: "en", label: "English" },
  { value: "ru", label: "Russian" },
  { value: "es", label: "Spanish" },
  { value: "de", label: "German" },
  { value: "fr", label: "French" },
  { value: "zh", label: "Chinese" },
  { value: "ja", label: "Japanese" },
] as const;

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number]["value"];

export interface LanguageSettings {
  interfaceLanguage: SupportedLanguage;
  conversationLanguage: SupportedLanguage;
  contentLanguage: SupportedLanguage;
}

export interface CsvRow {
  postId: string;
  date: string;
  text: string;
  impressions: number;
  likes: number;
  engagements: number;
  bookmarks: number;
  shares: number;
  newFollows: number;
  replies: number;
  reposts: number;
}

export interface CsvTopPost {
  text: string;
  impressions: number;
  engagements: number;
  likes: number;
}

export interface CsvSummary {
  totalPosts: number;
  dateRange: { from: string; to: string };
  avgImpressions: number;
  maxImpressions: number;
  totalNewFollows: number;
  avgEngagementRate: number;
  topPosts: CsvTopPost[];
}

// --- Analytics types (new pipeline: CSV → DB → Charts → Agent) ---

export type XPostType = "Post" | "Reply";

export const X_POST_TYPE_MAP: Record<string, XPostType> = {
  POST: "Post",
  REPLY: "Reply",
};

export const X_POST_TYPE_TO_PRISMA: Record<XPostType, string> = {
  Post: "POST",
  Reply: "REPLY",
};

export interface ContentCsvRow {
  postId: string;
  date: string;
  text: string;
  postLink: string;
  postType: XPostType;
  impressions: number;
  likes: number;
  engagements: number;
  bookmarks: number;
  shares: number;
  newFollowers: number;
  replies: number;
  reposts: number;
  profileVisits: number;
  detailExpands: number;
  urlClicks: number;
}

export interface OverviewCsvRow {
  date: string;
  impressions: number;
  likes: number;
  engagements: number;
  bookmarks: number;
  shares: number;
  newFollows: number;
  unfollows: number;
  replies: number;
  reposts: number;
  profileVisits: number;
  createPost: number;
  videoViews: number;
  mediaViews: number;
}

export interface AnalyticsSummary {
  dateRange: { from: string; to: string };
  periodDays: number;
  totalPosts: number;
  totalReplies: number;
  avgPostImpressions: number;
  avgReplyImpressions: number;
  maxPostImpressions: number;
  totalNewFollows: number;
  totalUnfollows: number;
  netFollowerGrowth: number;
  avgEngagementRate: number;
  avgProfileVisitsPerDay: number;
  topPosts: ContentCsvRow[];
  topReplies: ContentCsvRow[];
  dailyStats: {
    date: string;
    impressions: number;
    newFollows: number;
    unfollows: number;
    profileVisits: number;
    engagements: number;
  }[];
  postsByDay: {
    date: string;
    posts: number;
    replies: number;
  }[];
}

// --- Profile & Strategy types ---

export interface XProfile {
  name: string;
  username: string;
  bio: string;
  followers: string;
  following: string;
}

export interface StrategyAnalysisItem {
  id: string;
  weekStart: Date;
  recommendation: string;
  createdAt: Date;
  csvSummary: CsvSummary;
  searchQueries: string[];
  autoGenerated: boolean;
}

// --- Research & Daily Insight types ---

export interface ResearchSource {
  title: string;
  url: string;
  snippet: string;
}

export interface ResearchNoteItem {
  id: string;
  topic: string;
  summary: string;
  sources: ResearchSource[];
  queries: string[];
  createdAt: Date;
}

export interface DailyInsightContext {
  strategyAnalysisId: string | null;
  researchNoteIds: string[];
  daysOfStats: number;
}

export interface DailyInsightItem {
  id: string;
  date: Date;
  insights: string[];
  context: DailyInsightContext;
  createdAt: Date;
}

// --- Followers & Growth Tracking ---

export interface FollowersSnapshotItem {
  id: string;
  date: Date;
  followersCount: number;
  followingCount: number;
  deltaFollowers: number;
  deltaFollowing: number;
}

export interface GoalTrackingData {
  currentFollowers: number;
  targetFollowers: number;
  targetDate: Date;
  dailyAvgGrowth: number;
  projectedDate: Date | null;
  deviationDays: number;
  onTrack: boolean;
}

// --- Trends ---

export interface TrendItem {
  trendName: string;
  postCount: number;
  category?: string;
}

// --- Engagement Heatmap ---

export interface HeatmapCell {
  dayOfWeek: number; // 0=Mon, 6=Sun
  hour: number; // 0-23
  avgEngagementRate: number; // fraction (e.g. 0.042 = 4.2%)
  postCount: number;
}

// --- Plan Proposals ---

export const PROPOSAL_STATUSES = ["pending", "accepted", "rejected"] as const;
export type ProposalStatus = (typeof PROPOSAL_STATUSES)[number];

export type DayKey = "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";

/** Legacy one-time slot change (still supported for backward compat) */
export interface PlanChange {
  action: "add" | "remove" | "move";
  date: string;
  timeSlot: string;
  slotType: SlotType;
  reason: string;
}

/** Config-level change: modifies the recurring weekly ScheduleConfig template */
export interface ConfigChange {
  action: "add" | "remove";
  section: "replies" | "posts" | "threads" | "articles";
  time: string; // "HH:MM" 24h format, e.g. "08:00"
  days: Partial<Record<DayKey, boolean>>;
  reason: string;
}

/** Metrics snapshot captured at the time a proposal is created */
export interface MetricsSnapshot {
  avgImpressions: number;
  newFollowersPerWeek: number;
  engagementRate: number;
  date: string; // ISO date string
}

/** Past decision: accepted proposal with current metrics for effectiveness comparison */
export interface PastDecisionItem {
  date: string; // ISO date of acceptance
  changes: ConfigChange[];
  rationale: string; // proposal summary
  metricsAtDecision: MetricsSnapshot;
}

export interface PlanProposalItem {
  id: string;
  status: ProposalStatus;
  proposalType: "config" | "schedule";
  changes: PlanChange[] | ConfigChange[];
  summary: string;
  analysisId?: string;
  metricsSnapshot?: MetricsSnapshot;
  createdAt: Date;
}
