import { NextRequest, NextResponse } from "next/server";
import * as Sentry from "@sentry/nextjs";
import { anthropic } from "@ai-sdk/anthropic";
import { generateText, tool, stepCountIs } from "ai";
import { z } from "zod";
import { tavily } from "@tavily/core";
import { getStrategistPrompt, buildStrategistUserMessage } from "@/prompts/strategist";
import { getAnalyticsSummary, getAnalyticsDateRange } from "@/app/actions/analytics";
import { getFollowersHistoryInternal } from "@/app/actions/followers";
import { getLatestTrendsInternal } from "@/app/actions/trends";
import { getGoalTrackingData } from "@/app/actions/schedule";
import { getRecentResearchNotesInternal } from "@/app/actions/research";
import { saveAnalysisInternal, getAnalysesInternal } from "@/app/actions/strategist";
import { savePlanProposal, getAcceptedProposals } from "@/app/actions/plan-proposal";
import { getScheduleConfig } from "@/app/actions/schedule";
import { prisma } from "@/lib/prisma";
import { fetchUserData } from "@/lib/x-api";
import type { ConfigChange, MetricsSnapshot, PastDecisionItem } from "@/lib/types";

export const maxDuration = 120;

export async function GET(req: NextRequest) {
  const authHeader = req.headers.get("authorization");
  if (
    authHeader !== `Bearer ${process.env.CRON_SECRET}` &&
    req.cookies.get("auth")?.value !== "1"
  ) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const tavilyApiKey = process.env.TAVILY_API_KEY;
  if (!tavilyApiKey) {
    return NextResponse.json({ error: "TAVILY_API_KEY not configured" }, { status: 500 });
  }

  try {
    // TODO: multi-user — iterate over all users with X API tokens
    const users = await prisma.user.findMany({ select: { id: true } });
    const userId = users[0]?.id;
    if (!userId) {
      return NextResponse.json({ error: "No users found" }, { status: 422 });
    }

    // 1. Collect context in parallel
    const dateRange = await getAnalyticsDateRange();
    if (!dateRange) {
      return NextResponse.json(
        { error: "No analytics data available — import CSV first" },
        { status: 422 }
      );
    }

    // Last 30 days of analytics
    const thirtyDaysAgo = new Date(dateRange.to);
    thirtyDaysAgo.setUTCDate(thirtyDaysAgo.getUTCDate() - 30);
    const from30 = new Date(Math.max(thirtyDaysAgo.getTime(), dateRange.from.getTime()));

    const [
      summary,
      followersHistory,
      trends,
      researchNotes,
      goalData,
      previousAnalyses,
      scheduleConfig,
      acceptedProposals,
    ] = await Promise.all([
      getAnalyticsSummary(from30, dateRange.to),
      getFollowersHistoryInternal(userId, 30),
      getLatestTrendsInternal(),
      getRecentResearchNotesInternal(userId, 3),
      getGoalTrackingData(),
      getAnalysesInternal(userId),
      getScheduleConfig(),
      getAcceptedProposals(30),
    ]);

    // 2. Auto-fetch profile from X API (non-fatal if fails)
    let profile:
      | { name: string; username: string; bio: string; followers: string; following: string }
      | undefined;
    try {
      const userData = await fetchUserData();
      profile = {
        name: "",
        username: "",
        bio: "",
        followers: String(userData.followersCount),
        following: String(userData.followingCount),
      };
    } catch {
      // X API unavailable — proceed without profile
    }

    // 3. Previous strategy (most recent non-autoGenerated, or latest)
    const previousAnalysis = previousAnalyses[0]?.recommendation ?? undefined;

    // 4. Build week start string
    const weekStart = new Date().toISOString().split("T")[0]!;

    // 3b. Build past decisions for self-improvement loop
    const currentMetrics: MetricsSnapshot = {
      avgImpressions: summary.avgPostImpressions,
      newFollowersPerWeek: Math.round(
        summary.totalNewFollows / Math.max(summary.periodDays / 7, 1)
      ),
      engagementRate: summary.avgEngagementRate,
      date: weekStart,
    };

    const pastDecisions: PastDecisionItem[] = acceptedProposals
      .filter((p) => p.proposalType === "config" && p.metricsSnapshot)
      .map((p) => ({
        date: p.createdAt.toISOString().split("T")[0],
        changes: p.changes as ConfigChange[],
        rationale: p.summary,
        metricsAtDecision: p.metricsSnapshot!,
      }));

    // 5. Build user message
    const userMessage = buildStrategistUserMessage(
      summary,
      weekStart,
      profile,
      followersHistory,
      trends,
      undefined,
      researchNotes.map((n) => ({ topic: n.topic, summary: n.summary })),
      previousAnalysis,
      goalData ?? undefined,
      scheduleConfig ?? undefined,
      pastDecisions
    );

    // 6. Run analysis with Tavily web search
    const tavilyClient = tavily({ apiKey: tavilyApiKey });
    const searchQueries: string[] = [];

    const result = await generateText({
      model: anthropic("claude-sonnet-4-6"),
      system: getStrategistPrompt(),
      messages: [{ role: "user", content: userMessage }],
      tools: {
        webSearch: tool({
          description:
            "Search the web for X/Twitter growth strategies, algorithm updates, best posting times, engagement tactics",
          inputSchema: z.object({
            query: z.string().describe("Search query"),
          }),
          execute: async ({ query }) => {
            searchQueries.push(query);
            const response = await tavilyClient.search(query, {
              maxResults: 5,
              searchDepth: "basic",
            });
            return response.results.map((r) => ({
              title: r.title,
              url: r.url,
              snippet: r.content?.slice(0, 500) ?? "",
            }));
          },
        }),
      },
      stopWhen: stepCountIs(10),
    });

    const text = result.text;

    // 7. Build CsvSummary-compatible object for saveAnalysis
    const csvSummary = {
      totalPosts: summary.totalPosts + summary.totalReplies,
      dateRange: summary.dateRange,
      avgImpressions: summary.avgPostImpressions,
      maxImpressions: summary.maxPostImpressions,
      totalNewFollows: summary.totalNewFollows,
      avgEngagementRate: summary.avgEngagementRate,
      topPosts: summary.topPosts.slice(0, 5).map((p) => ({
        text: p.text.slice(0, 200),
        impressions: p.impressions,
        engagements: p.engagements,
        likes: p.likes,
      })),
    };

    // 8. Save analysis
    const saved = await saveAnalysisInternal(userId, {
      csvSummary,
      searchQueries,
      recommendation: text,
      weekStart: new Date(),
      autoGenerated: true,
    });

    // 9. Parse json:config-proposal block and save PlanProposal if found
    let proposalId: string | undefined;
    const proposalMatch = text.match(/```json:config-proposal\s*([\s\S]*?)```/);
    if (proposalMatch?.[1]) {
      try {
        const changes: ConfigChange[] = JSON.parse(proposalMatch[1].trim());
        if (Array.isArray(changes) && changes.length > 0) {
          // Extract a short summary from the strategy text
          const summaryMatch =
            text.match(/##[^#\n]*Стратегия[^#\n]*\n([\s\S]{0,300})/i) ??
            text.match(/##[^#\n]*Strategy[^#\n]*\n([\s\S]{0,300})/i);
          const proposalSummary =
            summaryMatch?.[1]?.trim().slice(0, 300) ??
            `Изменения в шаблон расписания (${changes.length} шт.) от ${weekStart}`;

          const proposal = await savePlanProposal({
            changes,
            summary: proposalSummary,
            analysisId: saved.id,
            proposalType: "config",
            metricsSnapshot: currentMetrics,
          });
          proposalId = proposal.id;
        }
      } catch {
        // JSON parse failed — skip proposal silently
      }
    }

    return NextResponse.json({
      ok: true,
      analysisId: saved.id,
      proposalId: proposalId ?? null,
      queriesUsed: searchQueries.length,
      periodFrom: summary.dateRange.from,
      periodTo: summary.dateRange.to,
    });
  } catch (err) {
    Sentry.captureException(err);
    console.error("[strategist]", err);
    return NextResponse.json(
      { ok: false, error: err instanceof Error ? err.message : String(err) },
      { status: 500 }
    );
  }
}
