"use server";

import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { requireUserId } from "@/lib/auth";
import type { CsvSummary, StrategyAnalysisItem } from "@/lib/types";

function toItem(row: {
  id: string;
  weekStart: Date;
  recommendation: string;
  createdAt: Date;
  csvSummary: unknown;
  searchQueries: string[];
  autoGenerated: boolean;
}): StrategyAnalysisItem {
  return {
    id: row.id,
    weekStart: row.weekStart,
    recommendation: row.recommendation,
    createdAt: row.createdAt,
    csvSummary: row.csvSummary as unknown as CsvSummary,
    searchQueries: row.searchQueries,
    autoGenerated: row.autoGenerated,
  };
}

// ---------------------------------------------------------------------------
// saveAnalysis
// ---------------------------------------------------------------------------

export async function saveAnalysis(data: {
  csvSummary: CsvSummary;
  searchQueries: string[];
  recommendation: string;
  weekStart: Date;
  autoGenerated?: boolean;
}): Promise<StrategyAnalysisItem> {
  const userId = await requireUserId();
  return _saveAnalysis(userId, data);
}

export async function saveAnalysisInternal(
  userId: string,
  data: {
    csvSummary: CsvSummary;
    searchQueries: string[];
    recommendation: string;
    weekStart: Date;
    autoGenerated?: boolean;
  }
): Promise<StrategyAnalysisItem> {
  return _saveAnalysis(userId, data);
}

async function _saveAnalysis(
  userId: string,
  data: {
    csvSummary: CsvSummary;
    searchQueries: string[];
    recommendation: string;
    weekStart: Date;
    autoGenerated?: boolean;
  }
): Promise<StrategyAnalysisItem> {
  const row = await prisma.strategyAnalysis.create({
    data: {
      userId,
      csvSummary: data.csvSummary as object,
      searchQueries: data.searchQueries,
      recommendation: data.recommendation,
      weekStart: data.weekStart,
      autoGenerated: data.autoGenerated ?? false,
    },
  });

  revalidatePath("/strategist");

  return toItem(row);
}

// ---------------------------------------------------------------------------
// getAnalyses
// ---------------------------------------------------------------------------

export async function getAnalyses(): Promise<StrategyAnalysisItem[]> {
  const userId = await requireUserId();
  return _getAnalyses(userId);
}

export async function getAnalysesInternal(userId: string): Promise<StrategyAnalysisItem[]> {
  return _getAnalyses(userId);
}

async function _getAnalyses(userId: string): Promise<StrategyAnalysisItem[]> {
  const rows = await prisma.strategyAnalysis.findMany({
    where: { userId },
    orderBy: { createdAt: "desc" },
    select: {
      id: true,
      weekStart: true,
      recommendation: true,
      createdAt: true,
      csvSummary: true,
      searchQueries: true,
      autoGenerated: true,
    },
  });

  return rows.map(toItem);
}

// ---------------------------------------------------------------------------
// getAnalysis (UI only)
// ---------------------------------------------------------------------------

export async function getAnalysis(id: string): Promise<StrategyAnalysisItem | null> {
  const userId = await requireUserId();
  const row = await prisma.strategyAnalysis.findUnique({ where: { id } });
  if (!row || row.userId !== userId) return null;

  return toItem(row);
}

// ---------------------------------------------------------------------------
// deleteAnalysis (UI only)
// ---------------------------------------------------------------------------

export async function deleteAnalysis(id: string): Promise<void> {
  const userId = await requireUserId();
  // Verify ownership before deleting
  const row = await prisma.strategyAnalysis.findUnique({ where: { id } });
  if (!row || row.userId !== userId) throw new Error("Not found");
  await prisma.strategyAnalysis.delete({ where: { id } });
  revalidatePath("/strategist");
}
